# Sample sheets
ENSEMBL: sample_sheet/ensembl.csv
NCBI: sample_sheet/ncbi.csv
RBBH: sample_sheet/114.csv
PUTATIVE: sample_sheet/putative.csv

# Latest version of STRING database
VERSION_STRING: v11.0

# METADATA Version (Should be bumped in each BioC update)
METADATA_VERSION: v002

# Bioconductor Version (for next coming)
BIOC_VERSION: 3.14
